knot_graphic=(function(){const draw_text=function(parent,text){const g=parent.group();const base=g.text(text).font({family:"DM Mono",size:18,anchor:"middle",}).fill("#333");return base;};const draw_symbol=function(parent,symbol){const g=parent.group();const bg=g.rect(20,20).move(-10,-15).fill("#4fffc7");const base=g.text(symbol.alpha).font({family:"DM Mono",size:18,anchor:"middle",}).fill("#333");let ind_g=null;if(symbol.index>=0)
ind_g=g.text(symbol.index.toString()).font({family:"DM Mono",size:9,anchor:"middle",}).fill("#333").dmove(base.bbox().w*0.7,-6);return[g,bg,base,ind_g];};const draw_tile=function(parent,datum,is_bar_crossing=false){if(datum==null||datum==="0")return null;const g=parent.group();const bg=g.rect(1,1).fill("#c7c7c7").opacity(0.0);switch(datum){case"0":break;case"*":g.circle(0.5).center(0.5,0.5).attr({fill:"#333"});g.polyline([0.5,1,0.5,0.5]).stroke({width:0.1,color:"#333"}).fill("none");break;case"|":g.polyline([0.5,0,0.5,1]).stroke({width:0.1,color:"#333"}).fill("none");break;case"-":g.polyline([0,0.5,1,0.5]).stroke({width:0.1,color:"#333"}).fill("none");break;case"+":bg.fill("#4fffc7");g.polyline([0.5,0,0.5,1]).stroke({width:0.1,color:"#333"}).fill("none");g.polyline([0,0.5,0.3,0.5]).stroke({width:is_bar_crossing?0.2:0.1,color:"#333"}).fill("none");g.polyline([0.7,0.5,1,0.5]).stroke({width:is_bar_crossing?0.2:0.1,color:"#333"}).fill("none");break;case"%":bg.fill("#4fffc7");g.polyline([0,0.5,1,0.5]).stroke({width:is_bar_crossing?0.2:0.1,color:"#333"}).fill("none");g.polyline([0.5,0,0.5,0.3]).stroke({width:0.1,color:"#333"}).fill("none");g.polyline([0.5,0.7,0.5,1]).stroke({width:0.1,color:"#333"}).fill("none");break;case"7":g.polyline([0,0.5,0.5,0.5,0.5,1.0]).stroke({width:0.1,color:"#333"}).fill("none");break;case"r":g.polyline([0.5,1.0,0.5,0.5,1.0,0.5]).stroke({width:0.1,color:"#333"}).fill("none");break;case"L":g.polyline([0.5,0,0.5,0.5,1.0,0.5]).stroke({width:0.1,color:"#333"}).fill("none");break;case"J":g.polyline([0,0.5,0.5,0.5,0.5,0]).stroke({width:0.1,color:"#333"}).fill("none");break;case"=":g.polyline([0,0.5,1,0.5]).stroke({width:0.2,color:"#333"}).fill("none");break;}
return[g,bg];};const draw_abstraction=function(knot_object,parent,width,height){const cx=width/2;const cy=height/2;const node_padding=20;const show_padding=40;const timeline=new SVG.Timeline();const final_show_start=0.75;const data=knot_object.data;for(let i=0;i<data.length;++i){for(let j=0;j<data[i].length;++j){const tile=draw_tile(parent,data[i][j],i===knot_object.bar_row_index);if(tile==null)continue;tile[0].center(cx+(j-data[i].length/2)*node_padding,cy+(i-data.length/2)*node_padding).size(node_padding,node_padding);tile[1].opacity(0.0);const traces=knot_object.get_trace(j,i);if(traces!=null){for(const t of traces){const start=(t/knot_object.trace_count)*final_show_start;const duration=final_show_start/knot_object.trace_count;svg_anim.fade_in(tile[1],timeline,duration,start);svg_anim.fade_out(tile[1],timeline,duration,start+duration);}}
svg_anim.fade_out(tile[0],timeline,0.05,final_show_start);}}
for(let i=0;i<knot_object.symbols.length;++i){const symbol=knot_object.symbols[i];const sg=draw_symbol(parent,symbol);sg[0].move(cx+(i-knot_object.symbols.length/2)*node_padding,10).opacity(0.0);const start=(symbol.trace/knot_object.trace_count)*final_show_start;const duration=final_show_start/knot_object.trace_count;svg_anim.fade_in(sg[0],timeline,duration,start);svg_anim.fade_out(sg[1],timeline,duration,start+duration);svg_anim.move(sg[0],timeline,0.1,final_show_start+0.05,cx+(i-knot_object.symbols.length/2)*show_padding,cy);svg_anim.settle(sg[2],timeline,0.1,final_show_start+0.15);if(sg[3]!=null)svg_anim.settle(sg[3],timeline,0.1,final_show_start+0.15);}
return timeline;};const draw_lemma=function(knot_objects,deltas,parent,width,height){const cx=width/2;const cy=height/2;const node_padding=20;const timeline=new SVG.Timeline();{const knot_object=knot_objects[0];const data=knot_object.data;for(let i=0;i<data.length;++i){for(let j=0;j<data[i].length;++j){const tile=draw_tile(parent,data[i][j],i===knot_object.bar_row_index);if(tile==null)continue;tile[0].center(cx+(j-data[i].length/2)*node_padding,cy+(i-data.length/2)*node_padding).size(node_padding,node_padding);svg_anim.fade_out(tile[0],timeline,0.2,0.4);}}}
{const knot_object=knot_objects[1];const data=knot_object.data;for(let i=0;i<data.length;++i){for(let j=0;j<data[i].length;++j){const tile=draw_tile(parent,data[i][j],i===knot_object.bar_row_index);if(tile==null)continue;tile[0].center(cx+(j-data[i].length/2)*node_padding,cy+(i-data.length/2)*node_padding).size(node_padding,node_padding);tile[0].opacity(0.0);svg_anim.fade_in(tile[0],timeline,0.2,0.4);}}}
const delta=deltas[0].data;const symbols=knot_objects[0].symbols;let final_length=delta.length;for(let i=0;i<delta.length;++i){if(isNaN(delta[i])){if(delta[i][0]==="-"){final_length-=1;}}}
for(let i=0;i<symbols.length;++i){const symbol=symbols[i];const sg=draw_symbol(parent,symbol);const ox=cx+(i-symbols.length/2)*node_padding;const oy=10;sg[0].move(ox,oy);let d=delta[i];if(isNaN(d)){if(d[d.length-1]==="p"){sg[1].fill("#4fc7ff");}
d=parseInt(d.substring(0,d.length-1));}else{sg[1].opacity(0.0);}
let dx=0;let dy=0;if(d<0){dx=cx+(i-final_length/2)*node_padding;dy=-100;}else{dx=cx+(d-final_length/2)*node_padding;dy=oy;}
svg_anim.move(sg[0],timeline,0.8,0.1,dx,dy);}
return timeline;};const draw_theorem=function(knot_objects,deltas,parent,width,height){const cx=width/2;const cy=height/2;const node_padding=20;const timeline=new SVG.Timeline();const start_time=0.1;const end_time=0.9;const section_duration=(end_time-start_time)/deltas.length;const gap_time=0.5*section_duration;const symbols=knot_objects[0].symbols;const manipulating_symbols=[];let loc_map=[];for(let i=0;i<symbols.length;++i){const symbol=symbols[i];const sg=draw_symbol(parent,symbol);const ox=cx+(i-symbols.length/2)*node_padding;const oy=cy;sg[0].move(ox,oy);sg[1].opacity(0.0);manipulating_symbols.push(sg);loc_map.push(i);}
for(let j=0;j<deltas.length;++j){const delta=deltas[j].data;const description=deltas[j].text;const section_start_time=start_time+section_duration*j;const description_g=draw_text(parent,description);description_g.move(20,-100);svg_anim.move(description_g,timeline,gap_time*0.8,section_start_time,20,10,"<>",false);svg_anim.fade_out(description_g,timeline,gap_time*0.2,section_start_time+section_duration);let final_length=delta.length;for(let i=0;i<delta.length;++i){if(isNaN(delta[i])){const tokens=delta[i].split("+");if(tokens.length>1){const sg=draw_symbol(parent,{alpha:tokens[1][0],index:parseInt(tokens[1].substring(1)),});const ox=cx+(i-manipulating_symbols.length/2)*node_padding;const oy=-100;sg[0].move(ox,oy);manipulating_symbols.push(sg);loc_map.splice(parseInt(tokens[0]),0,manipulating_symbols.length-1);}else if(delta[i][0]==="-"){final_length-=1;}}}
console.log(delta);let new_loc_map=[];for(let i=0;i<delta.length;++i){const sg=manipulating_symbols[loc_map[i]];const oy=cy;let d=delta[i];if(isNaN(d)){if(d[d.length-1]==="p"){svg_anim.change_fill(sg[1],timeline,gap_time,section_start_time,"#4fc7ff",true);}else if(d[d.length-1]==="m"){svg_anim.change_fill(sg[1],timeline,gap_time,section_start_time,"#4fffc7",true);}
d=parseInt(d.substring(0,d.length-1));}else{svg_anim.fade_out(sg[1],timeline,gap_time,section_start_time);}
let dx=0;let dy=0;if(d<0){dx=cx+(i-final_length/2)*node_padding;dy=-100;}else{dx=cx+(d-final_length/2)*node_padding;dy=oy;new_loc_map[d]=loc_map[i];}
svg_anim.move(sg[0],timeline,section_duration-gap_time,section_start_time+gap_time,dx,dy);}
loc_map=new_loc_map;}
for(const loc of loc_map){const sg=manipulating_symbols[loc];svg_anim.settle(sg[2],timeline,0.1,end_time);}
return timeline;};const draw_static=function(knot_object,parent,width,height){const cx=width/2;const cy=height/2;const node_padding=20;const data=knot_object.data;for(let i=0;i<data.length;++i){for(let j=0;j<data[i].length;++j){const tile=draw_tile(parent,data[i][j],i===knot_object.bar_row_index);if(tile==null)continue;tile[0].center(cx+(j-data[i].length/2)*node_padding,cy+(i-data.length/2)*node_padding).size(node_padding,node_padding);}}
for(let i=0;i<knot_object.symbols.length;++i){const symbol=knot_object.symbols[i];const sg=draw_symbol(parent,symbol);sg[0].move(cx+(i-knot_object.symbols.length/2)*node_padding,10);sg[1].opacity(0);}
return null;};const add_continuous_control=function(parent,svg,timeline,width,height){const control_group=svg.group();const bar_padding=width*0.05;const line=control_group.line(bar_padding,height-10,width-bar_padding,height-10);line.stroke({color:"#9990",width:5,linecap:"round"});const bar=control_group.line(0,height-10,bar_padding,height-10);bar.stroke({color:"#333f",width:7,linecap:"round"});svg_anim.move(bar,timeline,1.0,0,width-bar_padding,height-10,"-");let touching=null;let sx=null;let sy=null;let holding_bar=false;const on_bar_move=function(clientX,container_rect){const time=(clientX-container_rect.left-bar_padding)/(container_rect.width-bar_padding);timeline.time(Math.max(0,time));};parent.addEventListener("mousemove",(e)=>{on_bar_move(e.clientX,parent.getBoundingClientRect());});parent.addEventListener("touchstart",(e)=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY;touching=2;});parent.addEventListener("touchmove",(e)=>{if(touching>1){touching-=1;}else if(touching===1){if(Math.abs(e.touches[0].clientX-sx)>Math.abs(e.touches[0].clientY-sy)){holding_bar=true;line.stroke({color:"#9997"});}
touching=0;}else{if(holding_bar){on_bar_move(e.touches[0].clientX,parent.getBoundingClientRect());e.preventDefault();e.stopPropagation();}}});parent.addEventListener("touchend",(e)=>{holding_bar=false;line.stroke({color:"#9990"});});};const add_step_control=function(parent,svg,timeline,stops,width,height){const control_group=svg.group();let time=0;let handler=null;const play_to=function(t){if(handler!=null){clearInterval(handler);handler=null;}
handler=setInterval(()=>{timeline.time(time);if(Math.abs(time-t)<0.01){clearInterval(handler);handler=null;timeline.time(t);return;}
if(time<t){time+=0.01;}else if(time>t){time-=0.01;}},10);};const all_step_points=[];const clear_fill=function(){for(const step_point of all_step_points){step_point.fill("#333");}};let direction=1;let current_step=0;const on_click=function(selected_step){if(selected_step==null){selected_step=current_step+direction;if(selected_step<0){selected_step=1;direction=1;}else if(selected_step>=stops.length){selected_step=stops.length-2;direction=-1;}}
play_to(stops[selected_step]);clear_fill();all_step_points[selected_step].fill("#4fffc7");current_step=selected_step;};for(let i=0;i<stops.length;++i){const step_point=control_group.circle(10).center(width/2+(i-stops.length/2)*40,height-10).fill("#333").stroke({color:"#333f",width:2}).click(function(e){e.stopPropagation();e.preventDefault();on_click(i);}).on("mouseenter",function(){this.timeline().stop();this.timeline().play();}).on("mouseout",function(){});svg_anim.settle_stroke(step_point,null,1000.0,0);all_step_points.push(step_point);}
parent.addEventListener("click",(e)=>{on_click();});on_click(0);};const draw_graphic=function(parent,knot_objects,deltas){const container_rect=parent.getBoundingClientRect();const computed_style=getComputedStyle(parent);const width=container_rect.width-parseFloat(computed_style.paddingLeft)-parseFloat(computed_style.paddingRight);const height=container_rect.height-parseFloat(computed_style.paddingTop)-parseFloat(computed_style.paddingBottom);while(parent.firstChild)parent.firstChild.remove();const svg=SVG().addTo(parent).size("100%","100%");const graphic_group=svg.group();let timeline=null;if(parent.classList.contains("abstraction")){timeline=draw_abstraction(knot_objects[0],graphic_group,width,height);add_continuous_control(parent,svg,timeline,width,height);}else if(parent.classList.contains("lemma")){timeline=draw_lemma(knot_objects,deltas,graphic_group,width,height);add_step_control(parent,svg,timeline,[0,1.0],width,height);}else if(parent.classList.contains("theorem")){timeline=draw_theorem(knot_objects,deltas,graphic_group,width,height);add_continuous_control(parent,svg,timeline,width,height);}else{timeline=draw_static(knot_objects[0],graphic_group,width,height);}
return{clear:function(){timeline._runners=[];},};};const get_knot_data=function(knot_dom){const rows_str=knot_dom.innerHTML.split(";");knot_data=[];for(const row_str of rows_str){const trimmed=row_str.trim();if(trimmed.length==0)continue;const data=trimmed.split(",").map((x)=>x.trim());knot_data.push(data);}
return new Knot(knot_data);};window.addEventListener("load",()=>{for(const transform_dom of document.querySelectorAll(".knot-transform")){const knots=[];for(const knot_dom of transform_dom.querySelectorAll(".knot")){knots.push(get_knot_data(knot_dom));}
const deltas=[];for(const delta_dom of transform_dom.querySelectorAll(".delta-map")){deltas.push({data:JSON.parse(delta_dom.innerHTML),text:delta_dom.getAttribute("name"),});delta_dom.remove();}
draw_graphic(transform_dom,knots,deltas);}
for(const knot_dom of document.querySelectorAll(".knot")){draw_graphic(knot_dom,[get_knot_data(knot_dom)]);}});})();