const add_result_card=function(parent,production_data,count){const elem=document.createElement("div");elem.classList.add("result-card");const title=document.createElement("h3");title.innerText=`${production_data.craft_machine}`+" "+`${count}`;elem.appendChild(title);const lists=document.createElement("div");lists.classList.add("left-right");const product_list=document.createElement("ul");product_list.classList.add("product-list");for(const p of production_data.products){const item=document.createElement("li");item.innerText=`${p.id}`+" "+`${p.num_per_tick*count}`;product_list.appendChild(item);}
lists.appendChild(product_list);const require_list=document.createElement("ul");require_list.classList.add("require-list");for(const p of production_data.requires){const item=document.createElement("li");item.innerText=`${p.id}`+" "+`${p.num_per_tick*count}`;require_list.appendChild(item);}
lists.appendChild(require_list);elem.appendChild(lists);parent.appendChild(elem);};window.addEventListener("load",async function(){const r=await fetch("./data/resource_table.csv",{method:"GET",});if(r.status!==200){console.error("Failed to fetch craft table");return;}
const csv_data=await r.text();let data=[];const lines=csv_data.split("\n");const headers=lines[0].split(",");for(let i=1;i<lines.length;i++){const row=lines[i].split(",");const datum={craft_machine:row[5],craft_time:parseFloat(row[4]),craft_from:row[5],products:[{id:row[0],num_per_tick:parseFloat(row[1]),},],requires:[],};if(row[2]!==""){datum.products.push({id:row[2],num_per_tick:parseFloat(row[3]),});}
let component_index=6;while(component_index<row.length){if(row[component_index]!==""){datum.requires.push({id:row[component_index],num_per_tick:parseFloat(row[component_index+1]),});}
component_index+=2;}
data.push(datum);}
const result_list=document.getElementById("result");const all_products={};const all_bases={};const all_productions={};const all_production_details={};const product_speed_suggest=new Suggest_tag(document.querySelector("#product-speed"),(id)=>{const elem=document.createElement("span");elem.classList.add("button");elem.id=id;elem.innerText=all_products[id];return elem;},(id)=>{const elem=document.createElement("div");elem.classList.add("left-right");const label=document.createElement("label");label.innerText=all_products[id];const item_container=document.createElement("div");elem.appendChild(label);const item=document.createElement("input");item.id=`${id}-target-speed`;item.type="number";item.value=1;item.min=0;item.max=1000;item.step=0.25;item_container.appendChild(item);item_container.appendChild(document.createTextNode(" pcs/sec"));elem.appendChild(item_container);return elem;});const process_disable_suggest=new Suggest_tag(document.querySelector("#process-disabled"),(id)=>{const elem=document.createElement("span");elem.classList.add("button");elem.id=id;elem.innerText=all_productions[id];return elem;},(id)=>{const elem=document.createElement("span");elem.id=id;elem.innerText=all_productions[id];return elem;});for(const datum of data){for(const p of datum.products){const id=p.id.replaceAll(" ","_").replaceAll(".","_");if(all_products[id]==null){all_products[id]=p.id;}}
const is_base=datum.requires.length===0;if(is_base){for(const p of datum.products){const id=p.id.replaceAll(" ","_").replaceAll(".","_");all_bases[id]=p.id;}}
const prod_id=`${datum.products.map((p)=>p.id.replaceAll(" ","_").replaceAll(".","_")).join("_")}-from-${datum.requires.map((p)=>p.id.replaceAll(" ","_").replaceAll(".","_")).join("-")}`;all_productions[prod_id]=`${datum.craft_from}for ${datum.products.map((p)=>p.id).join(", ")}from ${datum.requires.map((p)=>p.id).join(", ")}`;all_production_details[prod_id]=datum;}
product_speed_suggest.add_items(Object.keys(all_products).map((id)=>{return{tag:id,display:all_products[id],};}));process_disable_suggest.add_items(Object.keys(all_productions).map((id)=>{return{tag:id,display:all_productions[id],};}));const require_resource_rate=Object.keys(all_products).map((id)=>{return Object.keys(all_productions).map((production_id)=>{return 0;});});const production_speed=Object.keys(all_products).map((id)=>{return Object.keys(all_productions).map((production_id)=>{return 0;});});for(const datum of data){const prod_id=`${datum.products.map((p)=>p.id.replaceAll(" ","_").replaceAll(".","_")).join("_")}-from-${datum.requires.map((p)=>p.id.replaceAll(" ","_").replaceAll(".","_")).join("-")}`;const prod_index=Object.keys(all_productions).indexOf(prod_id);for(const p of datum.products){const id=p.id.replaceAll(" ","_").replaceAll(".","_");const index=Object.keys(all_products).indexOf(id);production_speed[index][prod_index]=p.num_per_tick/datum.craft_time;}
for(const p of datum.requires){const id=p.id.replaceAll(" ","_").replaceAll(".","_");const index=Object.keys(all_products).indexOf(id);require_resource_rate[index][prod_index]=p.num_per_tick/datum.craft_time;}}
const highs_settings={locateFile:(file)=>"./thirdparties/"+file,};const highs=await Module(highs_settings);const calculate_button=document.getElementById("calculate-button");const result=document.getElementById("result");calculate_button.addEventListener("click",async function(e){const allowed_production=Object.keys(all_productions).map((id)=>{return!process_disable_suggest.get_selected().includes(id);});const target_speed=Object.keys(all_products).map((id)=>{const v=product_speed_suggest.get_selected().includes(id)?document.getElementById(`${id}-target-speed`).value:"";if(v==="")return 0;return parseFloat(v);});const params=op.build_matrices(require_resource_rate,production_speed,allowed_production,target_speed);const PROBLEM=`Minimize
obj:${params.obj}
Subject To
${params.constraints.map((c,i)=>{return`c${i}:${c}`;}).join("\n ")}
Bounds
${params.bounds.join("\n ")}
End`;const sol=highs.solve(PROBLEM);console.log(sol);const results=Object.keys(sol.Columns).filter((id)=>{return id.startsWith("x")&&sol.Columns[id].Primal>0;}).map((id,index)=>{return[sol.Columns[id].Index,sol.Columns[id].Primal];});while(result_list.firstChild)result_list.firstChild.remove();for(const r of results){const id=Object.keys(all_productions)[r[0]];const detail=all_production_details[id];console.log(`${id}:`+" "+`${r[1]}`);add_result_card(result_list,detail,r[1]);}});});